version: "3.9"

services:
  db:
    container_name: db
    restart: unless-stopped
    env_file:
      - api/config/env/prod.env
    environment:
      - NODE_ENV=prod
    image: "postgres:15.1"
    ports:
      - "5432:5432"
    networks:
      - memesChat

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - api/config/env/prod.env
    environment:
      - NODE_ENV=prod
    command: npm start
    volumes:
      - ./api:/api
    ports:
      - "3030:3030"
    depends_on:
      - db
    links:
      - db
    networks:
      - memesChat

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/config/env/prod.env
    command: npm start
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    links:
      - api
    networks:
      - memesChat

networks:
  memesChat: