#postgres server is visible as pgsql-server in pgadmin panel

version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.pl
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "8090:80"
    restart: unless-stopped
    links:
      - "postgres:pgsql-server"

volumes:
  postgres:
  pgadmin: