version: "3.9"

services:
  db:
    container_name: db
    restart: unless-stopped
    env_file:
      - api/config/env/prod.env
    environment:
      - NODE_ENV=prod
    volumes:
      - /data/postgres:/data/postgres
    image: "postgres:15.1"
    ports:
      - "5432:5432"
    networks:
      - memesChat

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - api/config/env/prod.env
    environment:
      - NODE_ENV=prod
    volumes:
      - ./api:/api
      - /api/node_modules
    ports:
      - "3030:3030"
    depends_on:
      - db
    links:
      - db
    networks:
      - memesChat

  ws:
    container_name: ws
    restart: unless-stopped
    build:
      context: ws
      dockerfile: Dockerfile
    env_file:
      - ws/config/env/prod.env
    environment:
      - NODE_ENV=prod
    volumes:
      - ./ws:/ws
      - /ws/node_modules
    ports:
      - "3040:3040"
    depends_on:
      - api
    links:
      - api
    networks:
      - memesChat

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/config/env/prod.env
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
      - ws
    links:
      - api
      - ws
    networks:
      - memesChat

networks:
  memesChat: